### ISSUE TITLE
Version mismatch in the Red Hat Catalog and in this repository?

### ISSUE THREAD

**Issue by jomeier** [kubevirt/hyperconverged-cluster-operator#853] opened 2020-10-02 06:51 UTC
Hi,

the Red Hat Catalog in the integrated OperatorHub reports this Operator (OpenShift Virtualization) being v2.4.1.

But the current Version reported by this repository seems to be v1.1.0 (or v1.2.0).

Which version is correct ?

I'd like to contribute in getting this Operator in the Community Catalog for OKD 4.5.

Thank you and greetings,

Josef

**Comment by tiraboschi** [comment] 2020-10-02 07:24
OpenShift Virtualization is a downstream Red Hat product built starting from this upstream project.
v2.4.1 is the latest version of Red Hat OpenShift Virtualization.

v1.1.0 is the latest version of this OpenSource project.

**Comment by jomeier** [comment] 2020-10-02 07:32
Thank you, tiraboschi. Does this mean, that the Operator built from the latest OpenSource Version should match the OpenShift Virtualization product regarding features or are there notable differences?

**Comment by tiraboschi** [comment] 2020-10-02 10:07
Red Hat policy is “upstream first”: we always work to get features integrated into open source projects before we integrate them into our product offerings.
So, to be fully honest, the opposite consideration can be true: we have a feature gating mechanism so you can eventually find features in the upstream project that are still not available in the downstream product because we consider them not stable/robust/well-integrate/well-documented enough to be shipped right now to customers.

**Comment by tiraboschi** [comment] 2020-10-02 10:09
Closing this as a duplicate of https://github.com/kubevirt/hyperconverged-cluster-operator/issues/606
We aim to be able to publish soon in `community-operators` again.

**Closed by tiraboschi** 2020-10-02 10:09 UTC
