### ISSUE TITLE
no matches for kind "HyperConverged" in version "hco.kubevirt.io/v1beta1"

### ISSUE THREAD

**Issue by disposab1e** [kubevirt/hyperconverged-cluster-operator#776] opened 2020-09-03 04:31 UTC
/kind bug

**What happened**:
Error: no matches for kind "HyperConverged" in version "hco.kubevirt.io/v1beta1"

**What you expected to happen**:
Successfull installation. 

**How to reproduce it (as minimally and precisely as possible)**:
Follow the installation [instructions](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/deploy/kustomize/README.md).

```
MARKETPLACE_MODE=false \
KVM_EMULATION=true \
CONTENT_ONLY=false \
./deploy/kustomize/deploy_kustomize.sh

```

**Environment**:
OKD 4.5
hyperconverged-cluster-operator master branch

**Comment by disposab1e** [comment] 2020-09-03 04:34
It seems there is no chance to install the operator from the 1.2.0 channel. Regardless which installation method.

**Comment by orenc1** [comment] 2020-09-03 07:54
Hi @disposab1e , thanks for you report.
The 1.2.0 version of the bundle image in quay.io/kubevirt/hco-container-registry:latest is not progressing because it's CSV expressed a required operator - node-maintenance-operator, which is not shipped in the same bundle.
Now, we decided to revert separating NMO outside of HCO (as in #771).
Once the image quay.io/kubevirt/hco-container-registry:latest will be updated with the current master's configuration, you should be able to install channel 1.2.0 using the command you've posted.
/cc @tiraboschi

**Comment by disposab1e** [comment] 2020-09-03 11:09
@orenc1 Thx for clarification! Means.... when I install node-maintenance-operator before, all should be fine?

**Comment by tiraboschi** [comment] 2020-09-04 12:23
No, sorry.
We rebuilt 1.2.0 CSV so now it also includes again node-maintenance-operator.
Can you please try again?
Please notice that 1.2.0 version is under continuous development on master branch while the latest stable release is 1.1.0 (probably it will be better to add some suffix to 1.2.0 to make more evident that it's still under developement)

**Comment by tiraboschi** [comment] 2020-09-11 16:47
I think we can close this one as a side effect of pre- builds after https://github.com/kubevirt/hyperconverged-cluster-operator/pull/771

Feel free to reopen if still reproducible

**Closed by tiraboschi** 2020-09-11 16:47 UTC
Labels: kind/bug
